#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://119.23.35.107:8761/eureka/
server:
  port: 8762
#是否开启熔断器
#feign:
#  hystrix:
#    enabled: true

spring:
  application:
    name: plantdisease


  datasource:
    loginUsername: liyutg
    loginPassword: l1206199288
    username: root
    password: toor
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/message?useUnicode=true&characterEncoding=utf-8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    #validationQuery: select 'x'
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

logging:
  level:
    com:
      spring:
        jiminshiro:
          mapper: debug

#  mybatis 配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  #  config-locations: classpath:mybatis-config.xml
  type-aliases-package: com.gaocimi.flashpig.entity
  configuration:
    map-underscore-to-camel-case: true

#   分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



###微信配置

wechat:
  miniapp:
    appid: wx216beccb226e15a8
    secret: 0355ddfe39dd854d911d0c19a99509d0
    token: 1998
    aesKey: 0355ddfe39dd854d911d0c19a99509d0
    msgDataFormat: JSON

#OSS存储设置
oss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  accessId: LTAI43x2yQ4rtTfF
  accessKey: LNpXhIs2CwFRCF6QPDzOEUoLtFeV4F
  bucket: gaocimi
  dir: answers
  dir2: static










